// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Миграции идут по прямому адресу базы: через пулер (Neon -pooler, PgBouncer) они могут не пройти.
    // Приложение само использует DATABASE_URL (src/lib/db.ts).
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
